#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// This is a test file generated by the currently most hyped tool "Chatgpt".
// The tool does a linear scan of the files given to it. So even comments that contain vulnerable functions will be flagged. 
// TODO: Improve the tool's language & comment detection.
int main() {
    system("echo Hello, this is a system command.");

    FILE* pipe = popen("ls -l", "r");
    if (pipe) {
        char buffer[128];
        while (fgets(buffer, sizeof(buffer), pipe) != NULL) {
            printf("%s", buffer);
        }
        pclose(pipe);
    }

    char source[] = "Copy me!";
    char destination[20];
    memcpy(destination, source, strlen(source) + 1);
    printf("Copied string: %s\n", destination);

    char buffer[10];
    memset(buffer, '*', sizeof(buffer) - 1);
    buffer[sizeof(buffer) - 1] = '\0';
    printf("Filled buffer: %s\n", buffer);

    char original[] = "Hello, World!";
    char copied[20];
    strcpy(copied, original);
    printf("Copied string: %s\n", copied);

    return 0;
}
